name: flutter_application_1
description: "MicroPOS - Aplicación de Gestión de Ventas y Punto de Venta Offline-First"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.20.2
  path_provider: ^2.1.6
  share_plus: ^12.0.2
  file_picker: 8.3.7
  pdf: ^3.13.0
  printing: ^5.15.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true